[tools]
ruby = { version = "latest", postinstall = "gem install solargraph" }
rust = "latest"
node = { version = "lts", postinstall = "npm install -g git-consistent" }
fnox = "latest"

[settings]
experimental = true
