[tools]
ruby = { version = "latest", postinstall = "gem install solargraph" }
node = { version = "lts", postinstall = "npm install -g git-consistent" }
rust = "latest"
yarn = "latest"
fnox = "latest"

[settings]
experimental = true
